CREATE TABLE `url` (
  `ID` int(4) NOT NULL AUTO_INCREMENT,
  `CLIENT_ID` varchar(20) DEFAULT NULL,
  `NAME` varchar(50) DEFAULT NULL,
  `DESCRIPTION` varchar(100) DEFAULT NULL,
  `ENVIRONMENT` varchar(20) DEFAULT NULL,
  `JOBS_HTTP_URL` varchar(50) DEFAULT NULL,
  `WEB_HTTP_URL` varchar(50) DEFAULT NULL,
  `WEB_HTTPS_URL` varchar(50) DEFAULT NULL,
  `UF_WEB_URL` varchar(50) DEFAULT NULL,
  `UF_SRV_URL` varchar(50) DEFAULT NULL,
  `UF_MC_URL` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `url_ibfk_1` (`CLIENT_ID`)
)