CREATE TABLE `server_details` (
  `ID` int(4) NOT NULL AUTO_INCREMENT,
  `CLIENT_ID` varchar(20) DEFAULT NULL,
  `NAME` varchar(50) DEFAULT NULL,
  `DESCRIPTION` varchar(100) DEFAULT NULL,
  `ENVIRONMENT` varchar(20) DEFAULT NULL,
  `TEAM` varchar(10) DEFAULT NULL,
  `TOMCAT_VERSION` varchar(40) DEFAULT NULL,
  `JAVA_VERSION` varchar(40) DEFAULT NULL,
  `EDIT_WHO` varchar(50) DEFAULT NULL,
  `EDIT_DATE` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00' ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`),
  KEY `server_details_ibfk_1` (`CLIENT_ID`)
) 