CREATE TABLE `client` (
  `ID` int(4) NOT NULL AUTO_INCREMENT,
  `CLIENT` varchar(50) DEFAULT NULL,
  `CLIENT_NAME` varchar(100) DEFAULT NULL,
  `DESCRIPTION` varchar(300) DEFAULT NULL,
  `SHARED_ENVIRONMENT` varchar(50) DEFAULT NULL,
  `WH_SITE` varchar(50) DEFAULT NULL,
  `EDIT_WHO` varchar(50) DEFAULT NULL,
  `EDIT_DATE` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00' ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`)
)