CREATE TABLE `server_instance` (
  `ID` int(4) NOT NULL AUTO_INCREMENT,
  `CLIENT_ID` varchar(20) DEFAULT NULL,
  `DESCRIPTION` varchar(100) DEFAULT NULL,
  `ENVIRONMENT` varchar(20) DEFAULT NULL,
  `SERVER_NAME` varchar(20) DEFAULT NULL,
  `INSTANCE1` varchar(50) DEFAULT NULL,
  `INSTANCE2` varchar(50) DEFAULT NULL,
  `INSTANCE3` varchar(50) DEFAULT NULL,
  `INSTANCE4` varchar(50) DEFAULT NULL,
  `EDIT_WHO` varchar(50) DEFAULT NULL,
  `EDIT_DATE` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00' ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`),
  KEY `SERVER_ID` (`CLIENT_ID`)
)