CREATE TABLE `todo` (
  `ID` int(4) NOT NULL AUTO_INCREMENT,
  `TITLE` varchar(100) NOT NULL,
  `IS_CHECKED` tinyint(4) DEFAULT NULL,
  `DUE_DATE` datetime DEFAULT NULL,
  `ASSIGNED_WHO` varchar(100) DEFAULT NULL,
  `PRIORITY` int(10) DEFAULT NULL,
  PRIMARY KEY (`ID`)
)